### ISSUE TITLE
Ability to edit the lang files

### ISSUE THREAD

**Issue by BrandHyde** [qwbarch/pixeldex#1]
Ability to edit messages etc from this mod, it would be lovely! Thank you for your hard work

**Comment by qwbarch** [comment]
Good suggestion! I'm currently busy so I'll add it sometime in the future when I have time.
Glad you're enjoying the mod. 😊

**Comment by BrandHyde** [comment]
I would also kindly like to add to this the ability to add color codes to the descriptions, and a reload command! If you have discord i'm happy to discuss paying for these updates to speed up the process a little bit as it's the main feature of my server.

thank you : branflake#6059

**Comment by qwbarch** [comment]
I've added you on discord to discuss features. I don't feel comfortable accepting money for basic features so I'll do it for free.
If anything, it's already nice to see it being used.

I really don't have time at the moment though, perhaps in a couple days I can do it. Good luck on your server!
